const SETTING_TYPE_OFFSET     = 0

export const TYPE_UINT8 = 0 << SETTING_TYPE_OFFSET
export const TYPE_INT8 = 1 << SETTING_TYPE_OFFSET
export const TYPE_UINT16 = 2 << SETTING_TYPE_OFFSET
export const TYPE_INT16 = 3 << SETTING_TYPE_OFFSET
export const TYPE_UINT32 = 4 << SETTING_TYPE_OFFSET
export const TYPE_FLOAT = 5 << SETTING_TYPE_OFFSET
export const TYPE_STRING = 6 << SETTING_TYPE_OFFSET
